DROP TABLE PAGOS CASCADE CONSTRAINTS;

DROP TABLE FACTURAS CASCADE CONSTRAINTS;

DROP TABLE INCIDENCIAS CASCADE CONSTRAINTS;

DROP TABLE MANTENIMIENTOS CASCADE CONSTRAINTS;

DROP TABLE RESERVAS CASCADE CONSTRAINTS;

DROP TABLE VEHICULOS CASCADE CONSTRAINTS;

DROP TABLE CLIENTES CASCADE CONSTRAINTS;

DROP TABLE CATEGORIAS_VEHICULO CASCADE CONSTRAINTS;