CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    DNI VARCHAR2(20) NOT NULL UNIQUE,
    TELEFONO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO NUMBER PRIMARY KEY,

    ID_CATEGORIA NUMBER NOT NULL,

    MATRICULA VARCHAR2(20) NOT NULL UNIQUE,

    MARCA VARCHAR2(50) NOT NULL,

    MODELO VARCHAR2(50) NOT NULL,

    ANIO NUMBER(4) NOT NULL,

    COMBUSTIBLE VARCHAR2(20) NOT NULL,

    PRECIO_DIA NUMBER(8,2) NOT NULL,

    ESTADO_VEHICULO VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL,

    CONSTRAINT FK_VEHICULO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS_VEHICULO(ID_CATEGORIA),

    CONSTRAINT CK_VEHICULOS_PRECIO
        CHECK (PRECIO_DIA > 0),

    CONSTRAINT CK_VEHICULOS_ESTADO
        CHECK (
            ESTADO_VEHICULO IN (
                'DISPONIBLE',
                'ALQUILADO',
                'MANTENIMIENTO'
            )
        )
);

CREATE TABLE RESERVAS (
    ID_RESERVA NUMBER PRIMARY KEY,

    ID_CLIENTE NUMBER NOT NULL,

    ID_VEHICULO NUMBER NOT NULL,

    FECHA_INICIO DATE NOT NULL,

    FECHA_FIN DATE NOT NULL,

    FECHA_RESERVA DATE DEFAULT SYSDATE NOT NULL,

    ESTADO_RESERVA VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,

     CONSTRAINT FK_RESERVA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE),

    CONSTRAINT FK_RESERVA_VEHICULO
        FOREIGN KEY (ID_VEHICULO)
        REFERENCES VEHICULOS(ID_VEHICULO),

    CONSTRAINT CK_RESERVA_FECHAS
    CHECK (FECHA_FIN > FECHA_INICIO),

    CONSTRAINT CK_RESERVA_ESTADO
    CHECK (
        ESTADO_RESERVA IN (
            'ACTIVA',
            'FINALIZADA',
            'CANCELADA'
        )
    )
);

CREATE TABLE FACTURAS (
    ID_FACTURA NUMBER PRIMARY KEY,

    ID_RESERVA NUMBER NOT NULL UNIQUE,

    FECHA_FACTURA DATE DEFAULT SYSDATE NOT NULL,

    IMPORTE_TOTAL NUMBER(10,2) NOT NULL,

    ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,

    CONSTRAINT FK_FACTURA_RESERVA
    FOREIGN KEY (ID_RESERVA)
    REFERENCES RESERVAS(ID_RESERVA),

    CONSTRAINT CK_FACTURA_IMPORTE
        CHECK(IMPORTE_TOTAL > 0),

    CONSTRAINT CK_FACTURA_ESTADO
        CHECK (
            ESTADO_PAGO IN (
                'PENDIENTE',
                'PAGADA',
                'ANULADA'
            )   
        )
);

CREATE TABLE PAGOS (

    ID_PAGO NUMBER PRIMARY KEY,

    ID_FACTURA NUMBER NOT NULL,

    FECHA_PAGO DATE DEFAULT SYSDATE NOT NULL,

    IMPORTE NUMBER(10,2) NOT NULL,

    METODO_PAGO VARCHAR(20) NOT NULL,

    CONSTRAINT FK_PAGO_FACTURA
        FOREIGN KEY (ID_FACTURA)
        REFERENCES FACTURAS(ID_FACTURA),

    CONSTRAINT CK_PAGO_IMPORTE
        CHECK (IMPORTE > 0),

    CONSTRAINT CK_PAGO_METODO
        CHECK (
            METODO_PAGO IN (
                'TARJETA',
                'EFECTIVO',
                'TRANSFERENCIA'
            )
        )
    );

CREATE TABLE MANTENIMIENTOS (

    ID_MANTENIMIENTO NUMBER PRIMARY KEY,

    ID_VEHICULO NUMBER NOT NULL,

    FECHA_MANTENIMIENTO DATE DEFAULT SYSDATE NOT NULL,

    DESCRIPCION VARCHAR2(200) NOT NULL,

    COSTE NUMBER(10,2) NOT NULL,

    CONSTRAINT FK_MANTENIMIENTO_VEHICULO
        FOREIGN KEY (ID_VEHICULO)
        REFERENCES VEHICULOS(ID_VEHICULO),

    CONSTRAINT CK_MANTENIMIENTO_COSTE
        CHECK (COSTE >= 0)
);