CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    DNI VARCHAR2(20) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL

    CONSTRAINT UK_CLIENTES_DNI
    UNIQUE(DNI),

    CONSTRAINT UK_CLIENTES_EMAIL
    UNIQUE(EMAIL)
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO NUMBER PRIMARY KEY,

    ID_CATEGORIA NUMBER NOT NULL,

    MATRICULA VARCHAR2(20) NOT NULL,

    MARCA VARCHAR2(50) NOT NULL,

    MODELO VARCHAR2(50) NOT NULL,

    ANIO NUMBER(4) NOT NULL,

    COMBUSTIBLE VARCHAR2(20) NOT NULL,

    PRECIO_DIA NUMBER(8,2) NOT NULL,

    ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL,

    CONSTRAINT UK_VEHICULOS_MATRICULA
        UNIQUE (MATRICULA),

    CONSTRAINT FK_VEHICULO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS_VEHICULO(ID_CATEGORIA),

    CONSTRAINT CK_VEHICULOS_PRECIO
        CHECK (PRECIO_DIA > 0),

    CONSTRAINT CK_VEHICULOS_ESTADO
        CHECK (
            ESTADO IN (
                'DISPONIBLE',
                'ALQUILADO',
                'MANTENIMIENTO'
            )
        )
);

CREATE TABLE RESERVAS (
    ID_RESERVA NUMBER PRIMARY KEY,

    ID_CLIENTE NUMBER NOT NULL,

    ID_VEHICULO NUMBER NOT NULL,

    FECHA_INICIO DATE NOT NULL,

    FECHA_FIN DATE NOT NULL,

    FECHA_RESERVA DATE DEFAULT SYSDATE NOT NULL,

    ESTADO VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,

    CONSTRAINT FK_RESERVA_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE),

    CONSTRAINT FK_RESERVA_VEHICULO
    FOREIGN KEY (ID_VEHICULO)
    REFERENCES VEHICULOS(ID_VEHICULO),

    CONSTRAINT CK_RESERVA_FECHAS
    CHECK (FECHA_FIN > FECHA_INICIO),

    CONSTRAINT CK_RESERVA_ESTADO
    CHECK (
        ESTADO IN (
            'ACTIVA',
            'FINALIZADA',
            'CANCELADA'
        )
    )
);