CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    DNI VARCHAR2(20) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL

    CONSTRAINT UK_CLIENTES_DNI
    UNIQUE(DNI),

    CONSTRAINT UK_CLIENTES_EMAIL
    UNIQUE(EMAIL)
);

CREATE TABLE VEHICULOS (
    ID_VEHICULO NUMBER PRIMARY KEY,

    ID_CATEGORIA NUMBER NOT NULL,

    MATRICULA VARCHAR2(20) NOT NULL,

    MARCA VARCHAR2(50) NOT NULL,

    MODELO VARCHAR2(50) NOT NULL,

    ANIO NUMBER(4) NOT NULL,

    COMBUSTIBLE VARCHAR2(20) NOT NULL,

    PRECIO_DIA NUMBER(8,2) NOT NULL,

    ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL,

    CONSTRAINT UK_VEHICULOS_MATRICULA
        UNIQUE (MATRICULA),

    CONSTRAINT FK_VEHICULO_CATEGORIA
        FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIAS_VEHICULO(ID_CATEGORIA),

    CONSTRAINT CK_VEHICULOS_PRECIO
        CHECK (PRECIO_DIA > 0),

    CONSTRAINT CK_VEHICULOS_ESTADO
        CHECK (
            ESTADO IN (
                'DISPONIBLE',
                'ALQUILADO',
                'MANTENIMIENTO'
            )
        )
);

