CREATE OR REPLACE TRIGGER TRG_BLOQUEAR_VEHICULO
AFTER INSERT ON RESERVAS
FOR EACH ROW
BEGIN
    UPDATE VEHICULOS
    SET ESTADO_VEHICULO = 'ALQUILADO'
    WHERE ID_VEHICULO = :NEW.ID_VEHICULO;
END;
/

