CREATE OR REPLACE PROCEDURE CANCELAR_RESERVA (
    p_id_reserva IN NUMBER
) IS
    v_id_vehiculo NUMBER;

BEGIN

    SELECT ID_VEHICULO INTO v_id_vehiculo FROM RESERVAS
    WHERE ID_RESERVA = p_id_reserva;

    UPDATE RESERVAS SET ESTADO_RESERVA = 'CANCELADA'
    WHERE ID_RESERVA = p_id_reserva;

    UPDATE VEHICULOS SET ESTADO_VEHICULO = 'DISPONIBLE'
    WHERE ID_VEHICULO = v_id_vehiculo;

END;
/